# SPDX-License-Identifier: MIT
version: '2'

tasks:
  default:
    cmds:
    - task --list
    silent: true

  test:
    desc: Test action
    env:
      INPUT_MAIN: 'curl git'
      INPUT_COMMUNITY: 'docker-cli'
      INPUT_TESTING: 'wget'
      INPUT_ARGS: '--help'
    cmds:
    - docker build --tag ffurrer/bats-action:latest .
    - docker run -it --rm --env INPUT_MAIN --env INPUT_COMMUNITY --env INPUT_TESTING --env INPUT_ARGS ffurrer/bats-action:latest

  lint:
    desc: Run all linters
    cmds:
    - task: shellcheck
    - task: yamllint
    - task: hadolint
    - task: markdownlint
    silent: true

  shellcheck:
    desc: Lint shell scripts
    cmds:
    - shellcheck --check-sourced --color=auto --format=tty --enable=all --source-path=./ --shell=bash --severity=style entrypoint.sh
    silent: true

  yamllint:
    desc: Lint YAML files
    cmds:
    - yamllint --config-file build/ci/.yamllint.yml --format auto --strict .
    silent: true

  hadolint:
    desc: Lint Dockerfiles
    cmds:
    - hadolint --format tty Dockerfile
    silent: true

  markdownlint:
    desc: Lint Markdown files
    cmds:
    - docker run -it --rm --volume "$(pwd):/work" tmknom/markdownlint:latest --config build/ci/.markdownlint.yml .
    silent: true
