# SPDX-License-Identifier: MIT
name: CI

on:
  push:
    branches:
    - master
    - feature/**
    - dependabot/**
    paths-ignore:
    - '**.md'
    - '.gitignore'

jobs:
  self-test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      uses: ./
      with:
        main: git curl
        community: docker-cli
        testing: wget
        args: --help
