# SPDX-License-Identifier: MIT
name: CI

on:
  push:
    branches:
    - master
    - feature/*
    paths-ignore:
    - '**.md'

jobs:
  self-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      uses: ./
      with:
        main: git curl
        community: docker-cli
        testing: wget
        args: --help

  shellcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Shellcheck
      uses: docker://koalaman/shellcheck:latest
      with:
        entrypoint: /bin/shellcheck
        args: '--check-sourced --color=auto --format=tty --enable=all --shell=bash --severity=style entrypoint.sh'

  yamllint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: yamllint
      uses: docker://ffurrer/yamllint:latest
      with:
        args: '--format auto --strict .'
