# SPDX-License-Identifier: MIT
name: shellcheck

on:
  push:
    branches:
    - main
    - feature/**
    - dependabot/**
    paths:
    - '**.sh'
    - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: shellcheck
      uses: docker://koalaman/shellcheck:latest
      with:
        entrypoint: /bin/shellcheck
        args: '--check-sourced --color=auto --format=tty --enable=all --source-path=./ --shell=bash --severity=style entrypoint.sh'
