# SPDX-License-Identifier: MIT
name: yamllint

on:
  push:
    branches:
    - master
    - feature/**
    - dependabot/**
    paths:
    - '**.ya?ml'
  pull_request:
    branches:
    - master

jobs:
  yamllint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: yamllint
      uses: docker://ffurrer/yamllint:latest
      with:
        entrypoint: /usr/bin/yamllint
        args: '--config-file build/ci/.yamllint.yml --format auto --strict .'
